import type { Metadata } from "next";
import "./globals.css";
import { Noto_Serif_Ahom } from "next/font/google";
const notoSerif = Noto_Serif_Ahom({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSerif.className}>{children}</body>
    </html>
  );
}
